<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CodingConnected.TLCProF.Testing</RootNamespace>
    <AssemblyName>CodingConnected.TLCProF.Testing</AssemblyName>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>CodingConnected.TLCProF.Testing</AssemblyTitle>
    <Product>CodingConnected.TLCProF.Testing</Product>
    <Copyright>Copyright © 2017</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
	<IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodingConnected.TLCProF\CodingConnected.TLCProF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.8.2" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>